<?php

return [
    'Kementerian Luar Negeri',
    'Kementerian Dalam Negeri',
    'Kementerian Pertahanan',
    'Kementerian Hukum dan Hak Asasi Manusia',
    'Kementerian Keuangan',
    'Kementerian Energi dan Sumber Daya Mineral',
    'Kementerian Perindustrian',
    'Kementerian Pertanian',
    'Kementerian Lingkungan Hidup dan Kehutanan',
    'Kementerian Perhubungan',
    'Kementerian Kelautan dan Perikanan',
    'Kementerian Pekerjaan Umum dan Perumahan Rakyat',
    'Kementerian Kesehatan',
    'Kementerian Pendidikan dan Kebudayaan',
    'Kementerian Sosial',
    'Kementerian Agama',
    'Kementerian Ketenagakerjaan',
    'Kementerian Sekretariat Negara',
    'Kejaksaan RI',
    'Markas Besar Tentara Nasional Indonesia (Mabes TNI)',
    'Kepolisian Negara Republik Indonesia (POLRI)',
    'Lembaga Administrasi Negara',
    'Arsip Nasional Republik Indonesia',
    'Badan Kepegawaian Negara',
    'Perpustakaan Nasional RI',
    'Badan Pusat Statistik',
    'Badan Standardisasi Nasional',
    'Badan Pengawas Tenaga Nuklir',
    'Badan Tenaga Nuklir Nasional',
    'Badan Intelijen Negara',
    'Badan Siber dan Sandi Negara',
    'Badan Urusan Logistik',
    'Lembaga Penerbangan dan Antariksa Nasional',
    'Badan Informasi Geospasial',
    'Badan Pengawasan Keuangan dan Pembangunan',
    'Lembaga Ilmu Pengetahuan Indonesia',
    'Badan Pengkajian dan Penerapan Teknologi',
    'Badan Koordinasi Penanaman Modal',
    'Kementerian Agraria dan Tata Ruang/Badan Pertanahan Nasional',
    'Badan Pengawas Obat dan Makanan',
    'Lembaga Informasi Nasional',
    'Lembaga Ketahanan Nasional RI',
    'Badan Pengembangan Kebudayaan dan Pariwisata',
    'Mahkamah Agung RI',
    'Pemerintah Provinsi Bali',
    'Pemerintah Provinsi Kep. Bangka Belitung',
    'Pemerintah Provinsi Banten',
    'Pemerintah Provinsi Bengkulu',
    'Pemerintah Provinsi Daerah Istimewa Yogyakarta',
    'Pemerintah Provinsi Daerah Khusus Ibukota Jakarta',
    'Pemerintah Provinsi Gorontalo',
    'Pemerintah Provinsi Jambi',
    'Pemerintah Provinsi Jawa Barat',
    'Pemerintah Provinsi Jawa Tengah',
    'Pemerintah Provinsi Jawa Timur',
    'Pemerintah Provinsi Kalimantan Barat',
    'Pemerintah Provinsi Kalimantan Selatan',
    'Pemerintah Provinsi Kalimantan Tengah',
    'Pemerintah Provinsi Kalimantan Timur',
    'Pemerintah Provinsi Lampung',
    'Pemerintah Provinsi Maluku',
    'Pemerintah Provinsi Maluku Utara',
    'Pemerintah Provinsi Aceh',
    'Pemerintah Provinsi NTB',
    'Pemerintah Provinsi NTT',
    'Pemerintah Provinsi Papua',
    'Pemerintah Provinsi Riau',
    'Pemerintah Provinsi Sulawesi Selatan',
    'Pemerintah Provinsi Sulawesi Tengah',
    'Pemerintah Provinsi Sulawesi Tenggara',
    'Pemerintah Provinsi Sumatera Barat',
    'Pemerintah Provinsi Sumatera Selatan',
    'Pemerintah Provinsi Sumatera Utara',
    'Pemerintah Provinsi Sulawesi Utara',
    'Badan Pemeriksa Keuangan',
    'Radio Republik Indonesia',
    'Kementerian Perdagangan',
    'Badan Meteorologi Klimatologi dan Geofisika',
    'Kementerian Pemberdayaan Perempuan dan Perlindungan Anak',
    'Sekretariat Kabinet',
    'Kementerian Komunikasi dan Informatika',
    'Setjen Komisi Nasional Hak Asasi Manusia',
    'Badan Narkotika Nasional',
    'Kementerian Pemuda dan Olahraga',
    'Kementerian Pariwisata',
    'Kementerian Koordinator Bidang Kemaritiman',
    'Pemerintah Provinsi Kepulauan Riau',
    'Pemerintah Provinsi Sulawesi Barat',
    'Pemerintah Provinsi Papua Barat',
    'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi',
    'Badan Pengawas Pasar modal dan Lembaga Keuangan',
    'Badan Pengkajian Ekonomi, Keuangan dan Kerjasama Internasional',
    'Badan Nasional Penanggulangan Bencana',
    'Televisi Republik Indonesia',
    'Sekretariat Jenderal Majelis Permusyawaratan Rakyat (MPR RI)',
    'Sekretariat Jenderal Dewan Perwakilan Rakyat (DPR RI)',
    'Kementerian Koordinator Bidang Politik Hukum dan Keamanan',
    'Kementerian Koordinator Bidang Perekonomian',
    'Kementerian Badan Usaha Milik Negara',
    'Kementerian Riset dan Teknologi / Badan Riset dan Inovasi',
    'Kementerian Koperasi dan Usaha Kecil dan Menengah',
    'Dewan Ketahanan Nasional',
    'Kementerian Perencanaan Pembangunan Nasional/Bappenas',
    'Badan Kependudukan dan Keluarga Berencana Nasional',
    'Setjen Komisi Pemilihan Umum',
    'Mahkamah Konstitusi',
    'Setjen Komisi Pemberantasan Korupsi',
    'Komisi Yudisial RI',
    'Badan Pelindungan Pekerja Migran Indonesia',
    'Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah',
    'Badan SAR Nasional',
    'Setjen Komisi Pengawas Persaingan Usaha',
    'Badan Pengawas Pemilihan Umum',
    'Markas Besar TNI Angkatan Laut',
    'Markas Besar TNI Anngkatan Darat',
    'Markas Besar TNI Angkatan Udara',
    'Pemerintah Provinsi Kalimantan Utara',
    'Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan',
    'Kementerian Desa, Pembangunan Daerah Tertinggal dan Transmigrasi',
    'Setjen Dewan Ketahanan Nasional (WANTANNAS)',
    'Badan Pengusahaan Kawasan Perdagangan Bebas dan Pelabuhan Bebas Batam',
    'Kepaniteraan dan Sekretariat Jenderal Mahkamah Konstitusi RI',
    'Sekretariat Jenderal Komisi Yudisial',
    'Setjen Dewan Perwakilan Daerah',
    'Badan Keamanan Laut RI',
    'Pusat Pelaporan dan Analisis Transaksi Keuangan',
    'Ombudsman Republik Indonesia',
    'Badan Nasional Penanggulangan Terorisme',
    'Komisi Aparatur Sipil Negara',
    'Badan Ekonomi Kreatif',
    'Pemerintah Kab. Aceh Besar',
    'Pemerintah Kab. Pidie',
    'Pemerintah Kab. Aceh Utara',
    'Pemerintah Kab. Aceh Timur',
    'Pemerintah Kab. Aceh Selatan',
    'Pemerintah Kab. Aceh Barat',
    'Pemerintah Kab. Aceh Tengah',
    'Pemerintah Kab. Aceh Tenggara',
    'Pemerintah Kab. Simeulue',
    'Pemerintah Kab. Bireuen',
    'Pemerintah Kab. Aceh Singkil',
    'Pemerintah Kab. Aceh Barat Daya',
    'Pemerintah Kab. Gayo Lues',
    'Pemerintah Kab. Aceh Tamiang',
    'Pemerintah Kab. Nagan Raya',
    'Pemerintah Kab. Aceh Jaya',
    'Pemerintah Kab. Bener Meriah',
    'Pemerintah Kab. Pidie Jaya',
    'Pemerintah Kota Sabang',
    'Pemerintah Kota Banda Aceh',
    'Pemerintah Kota Langsa',
    'Pemerintah Kota Lhokseumawe',
    'Pemerintah Kota Subulussalam',
    'Pemerintah Kab. Deli Serdang',
    'Pemerintah Kab. Karo',
    'Pemerintah Kab. Langkat',
    'Pemerintah Kab. Tapanuli Tengah',
    'Pemerintah Kab. Simalungun',
    'Pemerintah Kab. Labuhanbatu',
    'Pemerintah Kab. Dairi',
    'Pemerintah Kab. Tapanuli Utara',
    'Pemerintah Kab. Tapanuli Selatan',
    'Pemerintah Kab. Asahan',
    'Pemerintah Kab. Nias',
    'Pemerintah Kab. Toba Samosir',
    'Pemerintah Kab. Mandailing Natal',
    'Pemerintah Kab. Nias Selatan',
    'Pemerintah Kab. Humbang Hasundutan',
    'Pemerintah Kab. Pakpak Bharat',
    'Pemerintah Kab. Samosir',
    'Pemerintah Kab. Serdang Bedagai',
    'Pemerintah Kab. Padang Lawas',
    'Pemerintah Kab. Padang Lawas Utara',
    'Pemerintah Kab. Batubara',
    'Pemerintah Kab. Labuhanbatu Selatan',
    'Pemerintah Kab. Labuhanbatu Utara',
    'Pemerintah Kab. Nias Barat',
    'Pemerintah Kab. Nias Utara',
    'Pemerintah Kota Medan',
    'Pemerintah Kota Tebing Tinggi',
    'Pemerintah Kota Binjai',
    'Pemerintah Kota Pematangsiantar',
    'Pemerintah Kota Tanjungbalai',
    'Pemerintah Kota Sibolga',
    'Pemerintah Kota Padangsidimpuan',
    'Pemerintah Kota Gunung Sitoli',
    'Pemerintah Kab. Kampar',
    'Pemerintah Kab. Bengkalis',
    'Pemerintah Kab. Indragiri Hulu',
    'Pemerintah Kab. Indragiri Hilir',
    'Pemerintah Kab. Pelalawan',
    'Pemerintah Kab. Rokan Hulu',
    'Pemerintah Kab. Rokan Hilir',
    'Pemerintah Kab. Siak',
    'Pemerintah Kab. Kuantan Singingi',
    'Pemerintah Kab. Kepulauan Meranti',
    'Pemerintah Kota Pekanbaru',
    'Pemerintah Kota Dumai',
    'Pemerintah Kab. Agam',
    'Pemerintah Kab. Pasaman',
    'Pemerintah Kab. Limapuluh Kota',
    'Pemerintah Kab. Solok',
    'Pemerintah Kab. Padang Pariaman',
    'Pemerintah Kab. Pesisir Selatan',
    'Pemerintah Kab. Tanah Datar',
    'Pemerintah Kab. Sijunjung',
    'Pemerintah Kab. Kep. Mentawai',
    'Pemerintah Kab. Solok Selatan',
    'Pemerintah Kab. Dharmasraya',
    'Pemerintah Kab. Pasaman Barat',
    'Pemerintah Kota Bukittinggi',
    'Pemerintah Kota Padang Panjang',
    'Pemerintah Kota Sawahlunto',
    'Pemerintah Kota Solok',
    'Pemerintah Kota Padang',
    'Pemerintah Kota Payakumbuh',
    'Pemerintah Kota Pariaman',
    'Pemerintah Kab. Batang Hari',
    'Pemerintah Kab. Tanjung Jabung Barat',
    'Pemerintah Kab. Bungo',
    'Pemerintah Kab. Merangin',
    'Pemerintah Kab. Kerinci',
    'Pemerintah Kab. Sarolangun',
    'Pemerintah Kab. Tebo',
    'Pemerintah Kab. Muaro Jambi',
    'Pemerintah Kab. Tanjung Jabung Timur',
    'Pemerintah Kota Jambi',
    'Pemerintah Kota Sungai Penuh',
    'Pemerintah Kab. Musi Banyuasin',
    'Pemerintah Kab. Ogan Komering Ulu',
    'Pemerintah Kab. Muara Enim',
    'Pemerintah Kab. Lahat',
    'Pemerintah Kab. Musi Rawas',
    'Pemerintah Kab. Ogan Komering Ilir',
    'Pemerintah Kab. Banyuasin',
    'Pemerintah Kab. Ogan Komering Ulu Timur',
    'Pemerintah Kab. Ogan Komering Ulu Sel.',
    'Pemerintah Kab. Ogan Ilir',
    'Pemerintah Kab. Empat Lawang',
    'Pemerintah Kab. Musi Rawas Utara',
    'Pemerintah Kota Palembang',
    'Pemerintah Kota Pagar Alam',
    'Pemerintah Kota Lubuk Linggau',
    'Pemerintah Kota Prabumulih',
    'Pemerintah Kab. Penukal Abab Lematang Ilir',
    'Pemerintah Kab. Bangka',
    'Pemerintah Kab. Belitung',
    'Pemerintah Kab. Bangka Barat',
    'Pemerintah Kab. Bangka Tengah',
    'Pemerintah Kab. Bangka Selatan',
    'Pemerintah Kab. Belitung Timur',
    'Pemerintah Kota Pangkal Pinang',
    'Pemerintah Kab. Bengkulu Utara',
    'Pemerintah Kab. Bengkulu Selatan',
    'Pemerintah Kab. Rejang Lebong',
    'Pemerintah Kab. Kaur',
    'Pemerintah Kab. Seluma',
    'Pemerintah Kab. Mukomuko',
    'Pemerintah Kab. Kepahiang',
    'Pemerintah Kab. Lebong',
    'Pemerintah Kab. Bengkulu Tengah',
    'Pemerintah Kota Bengkulu',
    'Pemerintah Kab. Lampung Selatan',
    'Pemerintah Kab. Lampung Tengah',
    'Pemerintah Kab. Lampung Utara',
    'Pemerintah Kab. Lampung Barat',
    'Pemerintah Kab. Tulang Bawang',
    'Pemerintah Kab. Tanggamus',
    'Pemerintah Kab. Way Kanan',
    'Pemerintah Kab. Lampung Timur',
    'Pemerintah Kab. Pesawaran',
    'Pemerintah Kab. Tulang Bawang Barat',
    'Pemerintah Kab. Pringsewu',
    'Pemerintah Kab. Mesuji',
    'Pemerintah Kab. Pesisir Barat',
    'Pemerintah Kota Metro',
    'Pemerintah Kota Bandar Lampung',
    'Pemerintah Kab. Bogor',
    'Pemerintah Kab. Sukabumi',
    'Pemerintah Kab. Cianjur',
    'Pemerintah Kab. Bekasi',
    'Pemerintah Kab. Karawang',
    'Pemerintah Kab. Purwakarta',
    'Pemerintah Kab. Subang',
    'Pemerintah Kab. Bandung',
    'Pemerintah Kab. Sumedang',
    'Pemerintah Kab. Garut',
    'Pemerintah Kab. Tasikmalaya',
    'Pemerintah Kab. Ciamis',
    'Pemerintah Kab. Cirebon',
    'Pemerintah Kab. Kuningan',
    'Pemerintah Kab. Indramayu',
    'Pemerintah Kab. Majalengka',
    'Pemerintah Kab. Bandung Barat',
    'Pemerintah Kab. Pangandaran',
    'Pemerintah Kota Bandung',
    'Pemerintah Kota Bogor',
    'Pemerintah Kota Sukabumi',
    'Pemerintah Kota Cirebon',
    'Pemerintah Kota Bekasi',
    'Pemerintah Kota Depok',
    'Pemerintah Kota Cimahi',
    'Pemerintah Kota Tasikmalaya',
    'Pemerintah Kota Banjar',
    'Pemerintah Kab. Serang',
    'Pemerintah Kab. Pandeglang',
    'Pemerintah Kab. Lebak',
    'Pemerintah Kab. Tangerang',
    'Pemerintah Kota Tangerang',
    'Pemerintah Kota Cilegon',
    'Pemerintah Kota Serang',
    'Pemerintah Kota Tangerang Selatan',
    'Pemerintah Kab. Bantul',
    'Pemerintah Kab. Sleman',
    'Pemerintah Kab. Gunung Kidul',
    'Pemerintah Kab. Kulon Progo',
    'Pemerintah Kota Yogyakarta',
    'Pemerintah Kab. Semarang',
    'Pemerintah Kab. Kendal',
    'Pemerintah Kab. Demak',
    'Pemerintah Kab. Grobogan',
    'Pemerintah Kab. Pekalongan',
    'Pemerintah Kab. Batang',
    'Pemerintah Kab. Tegal',
    'Pemerintah Kab. Brebes',
    'Pemerintah Kab. Pati',
    'Pemerintah Kab. Kudus',
    'Pemerintah Kab. Pemalang',
    'Pemerintah Kab. Jepara',
    'Pemerintah Kab. Rembang',
    'Pemerintah Kab. Blora',
    'Pemerintah Kab. Banyumas',
    'Pemerintah Kab. Cilacap',
    'Pemerintah Kab. Purbalingga',
    'Pemerintah Kab. Banjarnegara',
    'Pemerintah Kab. Magelang',
    'Pemerintah Kab. Temanggung',
    'Pemerintah Kab. Wonosobo',
    'Pemerintah Kab. Purworejo',
    'Pemerintah Kab. Kebumen',
    'Pemerintah Kab. Klaten',
    'Pemerintah Kab. Boyolali',
    'Pemerintah Kab. Sragen',
    'Pemerintah Kab. Sukoharjo',
    'Pemerintah Kab. Karanganyar',
    'Pemerintah Kab. Wonogiri',
    'Pemerintah Kota Semarang',
    'Pemerintah Kota Salatiga',
    'Pemerintah Kota Pekalongan',
    'Pemerintah Kota Tegal',
    'Pemerintah Kota Magelang',
    'Pemerintah Kota Surakarta',
    'Pemerintah Kab. Gresik',
    'Pemerintah Kab. Mojokerto',
    'Pemerintah Kab. Sidoarjo',
    'Pemerintah Kab. Jombang',
    'Pemerintah Kab. Sampang',
    'Pemerintah Kab. Pamekasan',
    'Pemerintah Kab. Sumenep',
    'Pemerintah Kab. Bangkalan',
    'Pemerintah Kab. Bondowoso',
    'Pemerintah Kab. Situbondo',
    'Pemerintah Kab. Banyuwangi',
    'Pemerintah Kab. Jember',
    'Pemerintah Kab. Malang',
    'Pemerintah Kab. Pasuruan',
    'Pemerintah Kab. Probolinggo',
    'Pemerintah Kab. Lumajang',
    'Pemerintah Kab. Kediri',
    'Pemerintah Kab. Tulungagung',
    'Pemerintah Kab. Nganjuk',
    'Pemerintah Kab. Trenggalek',
    'Pemerintah Kab. Blitar',
    'Pemerintah Kab. Madiun',
    'Pemerintah Kab. Ngawi',
    'Pemerintah Kab. Magetan',
    'Pemerintah Kab. Ponorogo',
    'Pemerintah Kab. Pacitan',
    'Pemerintah Kab. Bojonegoro',
    'Pemerintah Kab. Tuban',
    'Pemerintah Kab. Lamongan',
    'Pemerintah Kota Surabaya',
    'Pemerintah Kota Mojokerto',
    'Pemerintah Kota Malang',
    'Pemerintah Kota Pasuruan',
    'Pemerintah Kota Probolinggo',
    'Pemerintah Kota Blitar',
    'Pemerintah Kota Kediri',
    'Pemerintah Kota Madiun',
    'Pemerintah Kota Batu',
    'Pemerintah Kab. Sambas',
    'Pemerintah Kab. Sanggau',
    'Pemerintah Kab. Sintang',
    'Pemerintah Kab. Mempawah',
    'Pemerintah Kab. Kapuas Hulu',
    'Pemerintah Kab. Ketapang',
    'Pemerintah Kab. Bengkayang',
    'Pemerintah Kab. Landak',
    'Pemerintah Kab. Melawi',
    'Pemerintah Kab. Sekadau',
    'Pemerintah Kab. Kubu Raya',
    'Pemerintah Kab. Kayong Utara',
    'Pemerintah Kota Pontianak',
    'Pemerintah Kota Singkawang',
    'Pemerintah Kab. Kapuas',
    'Pemerintah Kab. Barito Utara',
    'Pemerintah Kab. Barito Selatan',
    'Pemerintah Kab. Kotawaringin Timur',
    'Pemerintah Kab. Kotawaringin Barat',
    'Pemerintah Kab. Pulang Pisau',
    'Pemerintah Kab. Gunung Mas',
    'Pemerintah Kab. Lamandau',
    'Pemerintah Kab. Sukamara',
    'Pemerintah Kab. Murung Raya',
    'Pemerintah Kab. Katingan',
    'Pemerintah Kab. Seruyan',
    'Pemerintah Kab. Barito Timur',
    'Pemerintah Kota Palangka Raya',
    'Pemerintah Kab. Banjar',
    'Pemerintah Kab. Tanah Laut',
    'Pemerintah Kab. Tapin',
    'Pemerintah Kab. Hulu Sungai Selatan',
    'Pemerintah Kab. Hulu Sungai Tengah',
    'Pemerintah Kab. Barito Kuala',
    'Pemerintah Kab. Tabalong',
    'Pemerintah Kab. Kotabaru',
    'Pemerintah Kab. Hulu Sungai Utara',
    'Pemerintah Kab. Tanah Bumbu',
    'Pemerintah Kab. Balangan',
    'Pemerintah Kota Banjarmasin',
    'Pemerintah Kota Banjarbaru',
    'Pemerintah Kab. Kutai Kartanegara',
    'Pemerintah Kab. Paser',
    'Pemerintah Kab. Berau',
    'Pemerintah Kab. Kutai Barat',
    'Pemerintah Kab. Kutai Timur',
    'Pemerintah Kab. Penajam Paser Utara',
    'Pemerintah Kab. Mahakam Ulu',
    'Pemerintah Kota Samarinda',
    'Pemerintah Kota Balikpapan',
    'Pemerintah Kota Bontang',
    'Pemerintah Kab. Minahasa',
    'Pemerintah Kab. Bolaang Mongondow',
    'Pemerintah Kab. Kepulauan Sangihe',
    'Pemerintah Kab. Minahasa Selatan',
    'Pemerintah Kab. Kepulauan Talaud',
    'Pemerintah Kab. Minahasa Utara',
    'Pemerintah Kab. Bolaang Mongondow Utara',
    'Pemerintah Kab. Siau Tagulandang Biaro',
    'Pemerintah Kab. Minahasa Tenggara',
    'Pemerintah Kab. Bolaang Mongondow Selatan',
    'Pemerintah Kab. Bolaang Mongondow Timur',
    'Pemerintah Kota Manado',
    'Pemerintah Kota Bitung',
    'Pemerintah Kota Tomohon',
    'Pemerintah Kota KotaMobagu',
    'Pemerintah Kab. Gorontalo',
    'Pemerintah Kab. Boalemo',
    'Pemerintah Kab. Pohuwato',
    'Pemerintah Kab. Bone Bolango',
    'Pemerintah Kab. Gorontalo Utara',
    'Pemerintah Kota Gorontalo',
    'Pemerintah Kab. Poso',
    'Pemerintah Kab. Donggala',
    'Pemerintah Kab. Tolitoli',
    'Pemerintah Kab. Banggai',
    'Pemerintah Kab. Buol',
    'Pemerintah Kab. Morowali',
    'Pemerintah Kab. Banggai Kepulauan',
    'Pemerintah Kab. Parigi Moutong',
    'Pemerintah Kab. Tojo Una Una',
    'Pemerintah Kab. Sigi',
    'Pemerintah Kab. Banggai Laut',
    'Pemerintah Kab. Morowali Utara',
    'Pemerintah Kota Palu',
    'Pemerintah Kab. Pinrang',
    'Pemerintah Kab. Gowa',
    'Pemerintah Kab. Wajo',
    'Pemerintah Kab. Bone',
    'Pemerintah Kab. Tana Toraja',
    'Pemerintah Kab. Maros',
    'Pemerintah Kab. Luwu',
    'Pemerintah Kab. Sinjai',
    'Pemerintah Kab. Bulukumba',
    'Pemerintah Kab. Bantaeng',
    'Pemerintah Kab. Jeneponto',
    'Pemerintah Kab. Kepulauan Selayar',
    'Pemerintah Kab. Takalar',
    'Pemerintah Kab. Barru',
    'Pemerintah Kab. Sidenreng Rappang',
    'Pemerintah Kab. Pangkajene dan Kepulauan',
    'Pemerintah Kab. Soppeng',
    'Pemerintah Kab. Enrekang',
    'Pemerintah Kab. Luwu Utara',
    'Pemerintah Kab. Luwu Timur',
    'Pemerintah Kab. Toraja Utara',
    'Pemerintah Kota Makassar',
    'Pemerintah Kota Parepare',
    'Pemerintah Kota Palopo',
    'Pemerintah Kab. Konawe',
    'Pemerintah Kab. Buton',
    'Pemerintah Kab. Muna',
    'Pemerintah Kab. Kolaka',
    'Pemerintah Kab. Konawe Selatan',
    'Pemerintah Kab. Kolaka Utara',
    'Pemerintah Kab. Bombana',
    'Pemerintah Kab. Wakatobi',
    'Pemerintah Kab. Buton Utara',
    'Pemerintah Kab. Konawe Utara',
    'Pemerintah Kab. Kolaka Timur',
    'Pemerintah Kab. Konawe Kepulauan',
    'Pemerintah Kab. Buton Selatan',
    'Pemerintah Kab. Buton Tengah',
    'Pemerintah Kab. Muna Barat',
    'Pemerintah Kota Kendari',
    'Pemerintah Kota Baubau',
    'Pemerintah Kab. Buleleng',
    'Pemerintah Kab. Jembrana',
    'Pemerintah Kab. Klungkung',
    'Pemerintah Kab. Gianyar',
    'Pemerintah Kab. Karangasem',
    'Pemerintah Kab. Bangli',
    'Pemerintah Kab. Badung',
    'Pemerintah Kab. Tabanan',
    'Pemerintah Kota Denpasar',
    'Pemerintah Kab. Lombok Barat',
    'Pemerintah Kab. Lombok Tengah',
    'Pemerintah Kab. Lombok Timur',
    'Pemerintah Kab. Bima',
    'Pemerintah Kab. Sumbawa',
    'Pemerintah Kab. Dompu',
    'Pemerintah Kab. Sumbawa Barat',
    'Pemerintah Kab. Lombok Utara',
    'Pemerintah Kota Mataram',
    'Pemerintah Kota Bima',
    'Pemerintah Kab. Kupang',
    'Pemerintah Kab. Belu',
    'Pemerintah Kab. Timor Tengah Utara',
    'Pemerintah Kab. Timor Tengah Selatan',
    'Pemerintah Kab. Alor',
    'Pemerintah Kab. Sikka',
    'Pemerintah Kab. Flores Timur',
    'Pemerintah Kab. Ende',
    'Pemerintah Kab. Ngada',
    'Pemerintah Kab. Manggarai',
    'Pemerintah Kab. Sumba Timur',
    'Pemerintah Kab. Sumba Barat',
    'Pemerintah Kab. Lembata',
    'Pemerintah Kab. Rote Ndao',
    'Pemerintah Kab. Manggarai Barat',
    'Pemerintah Kab. Manggarai Timur',
    'Pemerintah Kab. Sumba Barat Daya',
    'Pemerintah Kab. Nagekeo',
    'Pemerintah Kab. Sumba Tengah',
    'Pemerintah Kab. Sabu Raijua',
    'Pemerintah Kab. Malaka',
    'Pemerintah Kota Kupang',
    'Pemerintah Kab. Maluku Tengah',
    'Pemerintah Kab. Maluku Tenggara',
    'Pemerintah Kab. Buru',
    'Pemerintah Kab. Maluku Tenggara Barat',
    'Pemerintah Kab. Kepulauan Aru',
    'Pemerintah Kab. Seram Bagian Barat',
    'Pemerintah Kab. Seram Bagian Timur',
    'Pemerintah Kab. Buru Selatan',
    'Pemerintah Kab. Maluku Barat Daya',
    'Pemerintah Kota Ambon',
    'Pemerintah Kota Tual',
    'Pemerintah Kab. Halmahera Barat',
    'Pemerintah Kab. Halmahera Tengah',
    'Pemerintah Kab. Kepulauan Sula',
    'Pemerintah Kab. Halmahera Selatan',
    'Pemerintah Kab. Halmahera Utara',
    'Pemerintah Kab. Halmahera Timur',
    'Pemerintah Kab. Pulau Morotai',
    'Pemerintah Kab. Pulau Taliabu',
    'Pemerintah Kota Ternate',
    'Pemerintah Kota Tidore Kepulauan',
    'Pemerintah Kab. Jayapura',
    'Pemerintah Kab. Biak Numfor',
    'Pemerintah Kab. Kepulauan Yapen',
    'Pemerintah Kab. Merauke',
    'Pemerintah Kab. Jayawijaya',
    'Pemerintah Kab. Nabire',
    'Pemerintah Kab. Puncak Jaya',
    'Pemerintah Kab. Paniai',
    'Pemerintah Kab. Mimika',
    'Pemerintah Kab. Boven Digoel',
    'Pemerintah Kab. Mappi',
    'Pemerintah Kab. Asmat',
    'Pemerintah Kab. Yahukimo',
    'Pemerintah Kab. Pegunungan Bintang',
    'Pemerintah Kab. Tolikara',
    'Pemerintah Kab. Sarmi',
    'Pemerintah Kab. Keerom',
    'Pemerintah Kab. Waropen',
    'Pemerintah Kab. Supiori',
    'Pemerintah Kab. Mamberamo Raya',
    'Pemerintah Kab. Mamberamo Tengah',
    'Pemerintah Kab. Lanny Jaya',
    'Pemerintah Kab. Yalimo',
    'Pemerintah Kab. Nduga',
    'Pemerintah Kab. Dogiyai',
    'Pemerintah Kab. Puncak',
    'Pemerintah Kab. Deiyai',
    'Pemerintah Kab. Intan Jaya',
    'Pemerintah Kota Jayapura',
    'Pemerintah Kab. Bintan',
    'Pemerintah Kab. Karimun',
    'Pemerintah Kab. Natuna',
    'Pemerintah Kab. Lingga',
    'Pemerintah Kab. Kepulauan Anambas',
    'Pemerintah Kota Batam',
    'Pemerintah Kota Tanjungpinang',
    'Pemerintah Kab. Sorong',
    'Pemerintah Kab. Sorong Selatan',
    'Pemerintah Kab. Raja Ampat',
    'Pemerintah Kab. Manokwari',
    'Pemerintah Kab. Teluk Bintuni',
    'Pemerintah Kab. Teluk Wondama',
    'Pemerintah Kab. Fak-Fak',
    'Pemerintah Kab. Kaimana',
    'Pemerintah Kab. Tambrauw',
    'Pemerintah Kab. Maybrat',
    'Pemerintah Kab. Pegunungan Arfak',
    'Pemerintah Kab. Manokwari Selatan',
    'Pemerintah Kota Sorong',
    'Pemerintah Kab. Mamuju Utara',
    'Pemerintah Kab. Mamuju',
    'Pemerintah Kab. Mamasa',
    'Pemerintah Kab. Polewali Mandar',
    'Pemerintah Kab. Majene',
    'Pemerintah Kab. Mamuju Tengah',
    'Pemerintah Kab. Bulungan',
    'Pemerintah Kab. Malinau',
    'Pemerintah Kab. Nunukan',
    'Pemerintah Kab. Tana Tidung',
    'Pemerintah Kota Tarakan',
    'Lembaga Perlindungan Saksi dan Korban',
    'Badan Pembinaan Ideologi Pancasila',
    'Markas Besar TNI',
];